# site config

# basic info

title: 'Get2Gather'
host: 'get2gather.eth.ericsson.se'
default_email: 'noreply@get2gather.eth.ericsson.se'
email_footer_whois: ""

# custom frontpage at app/views/customizations/[customization].html.slim

customization: 'get2gather'

# single location -> standalone: true
# multiple location, eg. cities -> standalone: false

standalone: true

# language settings

multilingual: true
default_language: 'en'

# login options

enable_facebook_login: false
enable_twitter_login: false

# facebook, twitter, g+ share buttons on the group pages

enable_share_buttons: false

# feedback box at the bottom

enable_feedback_box: false     # uservoice
enable_user_suggestions: true  # inbuilt box

# invite module

enable_invite_process: false

disable_gmaps: true

# discovery page limitations

# group_discovery_min_member_count: 3
# group_discovery_mandatory_header_image: true
