# site config

# basic info

title: 'Láthatatlan Egyetem'
host: 'lathatatlan.meetupedia.com'
default_email: 'noreply@lathatatlan.meetupedia.com'
email_footer_whois: ""

# custom frontpage at app/views/customizations/[customization].html.slim

customization: 'lathatatlan'

# single location -> standalone: true
# multiple location, eg. cities -> standalone: false

standalone: true

# language settings

multilingual: false
default_language: 'hu'

# login options

enable_facebook_login: true
enable_twitter_login: true

# facebook, twitter, g+ share buttons on the group pages

enable_share_buttons: false

# feedback box at the bottom

enable_feedback_box: false     # uservoice
enable_user_suggestions: true  # inbuilt box

# invite module

enable_invite_process: false
