development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: openmeetup
  pool: 5
  username: root
  password: pipeter
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: openmeetup_test
  pool: 5
  username: root
  password: pipeter
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: openmeetup
  pool: 5
  username: root
  password: pipeter
  socket: /var/run/mysqld/mysqld.sock
