standalone: true
customization: 'get2gather'
title: 'Get2Gather'
multilingual: true
default_language: 'en'
host: 'get2gather.hu'
default_email: 'noreply@get2gather.hu'
email_signature: "Üdvözlettel,\na Get2Gather csapata"

enable_facebook_login: false
enable_twitter_login: false
enable_share_buttons: false
enable_facebook_comments: false

enable_messages: false

enable_invite_process: false

enable_feedback_box: false
