standalone: false
title: 'Meetupedia'
multilingual: true
default_language: 'en'
host: 'meetupedia.com'
default_email: 'noreply@meetupedia.com'
email_signature: "Meetupedia Team"

enable_facebook_login: true
enable_twitter_login: false
enable_share_buttons: true

enable_messages: true

enable_invite_process: false
skip_invite_process_code: 'geronimo'

enable_feedback_box: true
